# Copyright (c) 2026 ads-tec Industrial IT GmbH, Germany
# Licensed under the BSD 2-Clause License. See LICENSE file for details.

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import json
import jsonrpcdevice

if __name__ == "__main__":
    dev = jsonrpcdevice.AdstecJSONRPCDevice("192.168.0.254", "admin", "admin")

    # complete packet filter configuration: flush all tables, re-insert
    # factory defaults, add a custom ruleset that drops TCP port 80
    filter_config = {
        "tableflush": [
            {"tablename": "selected_services"},
            {"tablename": "serv_Protocols"},
            {"tablename": "services"}
        ],
        "tableinsert": [
            {
                "tablename": "services",
                "data": [
                    # factory default rulesets
                    {"id": "1", "name": "ARP", "description": "ARP address resolution",
                     "layer_id": "1", "def_serv": "1",
                     "src_interf_name": "*", "des_interf_name": "*", "fac_def_pos": "1"},
                    {"id": "2", "name": "ICMP_L2",
                     "description": "Allow all Layer 2 ICMP packets",
                     "layer_id": "1", "def_serv": "1",
                     "src_interf_name": "*", "des_interf_name": "*", "fac_def_pos": ""},
                    {"id": "3", "name": "ICMP_L3",
                     "description": "Allow all Layer 3 ICMP packets",
                     "layer_id": "2", "def_serv": "1",
                     "src_interf_name": "*", "des_interf_name": "*", "fac_def_pos": ""},
                    {"id": "4", "name": "Allow_L2",
                     "description": "Allow all L2 traffic",
                     "layer_id": "1", "def_serv": "1",
                     "src_interf_name": "*", "des_interf_name": "*", "fac_def_pos": "2"},
                    {"id": "5", "name": "Allow_L3",
                     "description": "Allow all L3 traffic",
                     "layer_id": "2", "def_serv": "1",
                     "src_interf_name": "*", "des_interf_name": "*", "fac_def_pos": "3"},
                    {"id": "6", "name": "Block_L2",
                     "description": "Block all L2 traffic",
                     "layer_id": "1", "def_serv": "1",
                     "src_interf_name": "*", "des_interf_name": "*", "fac_def_pos": ""},
                    {"id": "7", "name": "Block_L3",
                     "description": "Block all L3 traffic",
                     "layer_id": "2", "def_serv": "1",
                     "src_interf_name": "*", "des_interf_name": "*", "fac_def_pos": ""},
                    {"id": "8", "name": "Log_L2",
                     "description": "Log and block all packets.",
                     "layer_id": "1", "def_serv": "1",
                     "src_interf_name": "*", "des_interf_name": "*", "fac_def_pos": ""},
                    {"id": "999", "name": "Log_L3",
                     "description": "Log and block all packets.",
                     "layer_id": "2", "def_serv": "1",
                     "src_interf_name": "*", "des_interf_name": "*", "fac_def_pos": ""},
                    # custom ruleset
                    {"id": "1000", "name": "FATT_Block_TCP80",
                     "description": "Drop and Log TCP Port 80",
                     "layer_id": "2", "def_serv": "0",
                     "src_interf_name": "*", "des_interf_name": "*", "fac_def_pos": ""}
                ]
            },
            {
                "tablename": "serv_Protocols",
                "data": [
                    # factory default rules
                    {"id": "1", "service_id": "1", "protocol": "ARP",
                     "action_id": "1", "log_active": "0", "alarm_active": "0",
                     "description": "allow_all_arp", "icmp_type": "", "icmp_rej_type": "",
                     "limitpack": "", "position": "1",
                     "src_mac_add": "*", "src_ip_add": "", "src_netmask": "",
                     "src_port": "", "des_mac_add": "*", "des_ip_add": "",
                     "des_netmask": "", "des_port": "",
                     "prot_hex": "10", "prot_transport": "", "state_type_id": "",
                     "nat_ip": "", "nat_port": "", "states": "", "statevalue": "",
                     "revert": "", "hide": "",
                     "sigcheck_vpn": "", "sig_vpn": "",
                     "sigcheck_cut": "", "sig_cut": "",
                     "sigcheck_vpnup": "", "sig_vpnup": "", "audit_active": "0"},
                    {"id": "2", "service_id": "2", "protocol": "IPV4",
                     "action_id": "1", "log_active": "0", "alarm_active": "0",
                     "description": "any_ICMP_type", "icmp_type": "", "icmp_rej_type": "",
                     "limitpack": "", "position": "1",
                     "src_mac_add": "*", "src_ip_add": "*", "src_netmask": "*",
                     "src_port": "", "des_mac_add": "*", "des_ip_add": "*",
                     "des_netmask": "*", "des_port": "",
                     "prot_hex": "", "prot_transport": "1", "state_type_id": "",
                     "nat_ip": "", "nat_port": "", "states": "", "statevalue": "",
                     "revert": "", "hide": "",
                     "sigcheck_vpn": "", "sig_vpn": "",
                     "sigcheck_cut": "", "sig_cut": "",
                     "sigcheck_vpnup": "", "sig_vpnup": "", "audit_active": "0"},
                    {"id": "3", "service_id": "3", "protocol": "ICMP",
                     "action_id": "1", "log_active": "0", "alarm_active": "0",
                     "description": "ICMP_L3", "icmp_type": "any", "icmp_rej_type": "",
                     "limitpack": "", "position": "1",
                     "src_mac_add": "", "src_ip_add": "*", "src_netmask": "*",
                     "src_port": "", "des_mac_add": "", "des_ip_add": "*",
                     "des_netmask": "*", "des_port": "",
                     "prot_hex": "", "prot_transport": "", "state_type_id": "1",
                     "nat_ip": "", "nat_port": "", "states": "", "statevalue": "",
                     "revert": "", "hide": "",
                     "sigcheck_vpn": "", "sig_vpn": "",
                     "sigcheck_cut": "", "sig_cut": "",
                     "sigcheck_vpnup": "", "sig_vpnup": "", "audit_active": "0"},
                    {"id": "4", "service_id": "4", "protocol": "*",
                     "action_id": "1", "log_active": "0", "alarm_active": "0",
                     "description": "allow_all", "icmp_type": "", "icmp_rej_type": "",
                     "limitpack": "", "position": "1",
                     "src_mac_add": "*", "src_ip_add": "", "src_netmask": "",
                     "src_port": "", "des_mac_add": "*", "des_ip_add": "",
                     "des_netmask": "", "des_port": "",
                     "prot_hex": "", "prot_transport": "", "state_type_id": "",
                     "nat_ip": "", "nat_port": "", "states": "", "statevalue": "",
                     "revert": "", "hide": "",
                     "sigcheck_vpn": "", "sig_vpn": "",
                     "sigcheck_cut": "", "sig_cut": "",
                     "sigcheck_vpnup": "", "sig_vpnup": "", "audit_active": "0"},
                    {"id": "5", "service_id": "5", "protocol": "*",
                     "action_id": "1", "log_active": "0", "alarm_active": "0",
                     "description": "allow_all", "icmp_type": "", "icmp_rej_type": "",
                     "limitpack": "", "position": "1",
                     "src_mac_add": "", "src_ip_add": "*", "src_netmask": "*",
                     "src_port": "", "des_mac_add": "", "des_ip_add": "*",
                     "des_netmask": "*", "des_port": "",
                     "prot_hex": "", "prot_transport": "", "state_type_id": "1",
                     "nat_ip": "", "nat_port": "", "states": "", "statevalue": "",
                     "revert": "", "hide": "",
                     "sigcheck_vpn": "", "sig_vpn": "",
                     "sigcheck_cut": "", "sig_cut": "",
                     "sigcheck_vpnup": "", "sig_vpnup": "", "audit_active": "0"},
                    {"id": "6", "service_id": "6", "protocol": "*",
                     "action_id": "2", "log_active": "0", "alarm_active": "0",
                     "description": "drop_all", "icmp_type": "", "icmp_rej_type": "",
                     "limitpack": "", "position": "1",
                     "src_mac_add": "*", "src_ip_add": "", "src_netmask": "",
                     "src_port": "", "des_mac_add": "*", "des_ip_add": "",
                     "des_netmask": "", "des_port": "",
                     "prot_hex": "", "prot_transport": "", "state_type_id": "",
                     "nat_ip": "", "nat_port": "", "states": "", "statevalue": "",
                     "revert": "", "hide": "",
                     "sigcheck_vpn": "", "sig_vpn": "",
                     "sigcheck_cut": "", "sig_cut": "",
                     "sigcheck_vpnup": "", "sig_vpnup": "", "audit_active": "0"},
                    {"id": "7", "service_id": "7", "protocol": "*",
                     "action_id": "2", "log_active": "0", "alarm_active": "0",
                     "description": "drop_all", "icmp_type": "", "icmp_rej_type": "",
                     "limitpack": "", "position": "1",
                     "src_mac_add": "", "src_ip_add": "*", "src_netmask": "*",
                     "src_port": "", "des_mac_add": "", "des_ip_add": "*",
                     "des_netmask": "*", "des_port": "",
                     "prot_hex": "", "prot_transport": "", "state_type_id": "1",
                     "nat_ip": "", "nat_port": "", "states": "", "statevalue": "",
                     "revert": "", "hide": "",
                     "sigcheck_vpn": "", "sig_vpn": "",
                     "sigcheck_cut": "", "sig_cut": "",
                     "sigcheck_vpnup": "", "sig_vpnup": "", "audit_active": "0"},
                    {"id": "8", "service_id": "8", "protocol": "*",
                     "action_id": "2", "log_active": "1", "alarm_active": "0",
                     "description": "Log", "icmp_type": "", "icmp_rej_type": "",
                     "limitpack": "", "position": "1",
                     "src_mac_add": "*", "src_ip_add": "", "src_netmask": "",
                     "src_port": "", "des_mac_add": "*", "des_ip_add": "",
                     "des_netmask": "", "des_port": "",
                     "prot_hex": "", "prot_transport": "", "state_type_id": "",
                     "nat_ip": "", "nat_port": "", "states": "", "statevalue": "",
                     "revert": "", "hide": "",
                     "sigcheck_vpn": "", "sig_vpn": "",
                     "sigcheck_cut": "", "sig_cut": "",
                     "sigcheck_vpnup": "", "sig_vpnup": "", "audit_active": "0"},
                    {"id": "9", "service_id": "999", "protocol": "*",
                     "action_id": "2", "log_active": "1", "alarm_active": "0",
                     "description": "Log", "icmp_type": "", "icmp_rej_type": "",
                     "limitpack": "", "position": "1",
                     "src_mac_add": "", "src_ip_add": "*", "src_netmask": "*",
                     "src_port": "", "des_mac_add": "", "des_ip_add": "*",
                     "des_netmask": "*", "des_port": "",
                     "prot_hex": "", "prot_transport": "", "state_type_id": "1",
                     "nat_ip": "", "nat_port": "", "states": "", "statevalue": "",
                     "revert": "", "hide": "",
                     "sigcheck_vpn": "", "sig_vpn": "",
                     "sigcheck_cut": "", "sig_cut": "",
                     "sigcheck_vpnup": "", "sig_vpnup": "", "audit_active": "0"},
                    # custom rule: drop and log TCP port 80
                    {"id": "10", "service_id": "1000", "protocol": "TCP",
                     "action_id": "2", "log_active": "1", "alarm_active": "1",
                     "description": "drop80", "icmp_type": "", "icmp_rej_type": "",
                     "limitpack": "", "position": "1",
                     "src_mac_add": "", "src_ip_add": "*", "src_netmask": "255.255.255.255",
                     "src_port": "*", "des_mac_add": "", "des_ip_add": "*",
                     "des_netmask": "255.255.255.255", "des_port": "80",
                     "prot_hex": "", "prot_transport": "", "state_type_id": "1",
                     "nat_ip": "", "nat_port": "",
                     "states": "NEW,RELATED,ESTABLISHED", "statevalue": "",
                     "revert": "", "hide": "",
                     "sigcheck_vpn": "0", "sig_vpn": "0",
                     "sigcheck_cut": "1", "sig_cut": "1",
                     "sigcheck_vpnup": "0", "sig_vpnup": "0",
                     "audit_active": "1"}
                ]
            },
            {
                "tablename": "selected_services",
                "data": [
                    {"id": "1", "serv_id": "1", "days": "", "time_active": "0",
                     "time_start": "", "time_stop": "", "position": "1"},
                    {"id": "2", "serv_id": "4", "days": "", "time_active": "0",
                     "time_start": "", "time_stop": "", "position": "2"},
                    {"id": "3", "serv_id": "5", "days": "", "time_active": "0",
                     "time_start": "", "time_stop": "", "position": "2"},
                    {"id": "4", "serv_id": "1000", "days": "", "time_active": "0",
                     "time_start": "", "time_stop": "", "position": "1"}
                ]
            }
        ]
    }

    dev.call("config", "import_config", jsondata=filter_config)
    print("Packet filter configuration imported successfully")

    dev.logout()
